spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: mongodb://localhost:27017/urls
  application:
    name: url-shortener
server:
  port: 8080
  error:
    whitelabel:
      enabled: false